---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# SWA notes - add ciphers to communicate over httpapi towards the EOS device. 
ansible_httpapi_ciphers: AES256-SHA:DHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA

# AAA Authorization
aaa_authorization:
  exec:
    default: local

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true


ip_name_servers:
  - ip_address: 1.1.1.1
    vrf: default
  - ip_address: 8.8.8.8
    vrf: default
ntp:
  servers:
  - name: time.google.com
    preferred: true
    vrf: default
    iburst: true

# clock:
#   timezone: EST5EDT

ip_routing: true
service_routing_protocols_model: multi-agent

management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true

# spanning_tree:
#   mode: mstp

logging:
  monitor: "debugging"
   
daemon_terminattr:
  cvaddrs:
  - apiserver.cv-staging.corp.arista.io:443
  cvauth:
    method: token-secure
    token_file: /tmp/cv-onboarding-token
  # cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  # ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: true

sflow:
  sample: 500
  polling_interval: 5
  destinations:
    - destination: 127.0.0.1
  # source_interface: Vlan224
  run: true