---
dps_interfaces:
  - name: 'Dps1'
    shutdown: false
    flow_tracker:
      hardware: WAN_FLOW_TRACKER
vxlan_interface:
  Vxlan1:
    description: VTEP_Termination
    vxlan:
      source_interface: Loopback0
      udp_port: 4789
      vrfs:
        - name: SITE_TRAFFIC
          vni: 250
        - name: default
          vni: 101
vrfs:
  - name: MGMT
    ip_routing: false
  - name: SITE_TRAFFIC
    ip_routing: true

flow_tracking:
  hardware:
    trackers:
      - name: WAN_FLOW_TRACKER
        record_export:
          on_inactive_timeout: 70000
          on_interval: 5000
        exporters:
          - name: EXPORTER
            collector:
              host: 127.0.0.1
            local_interface: Loopback0
            template_interval: 5000
    shutdown: false