hostname: S-2B
mgmt_ip_address: 172.16.1.103/24
eth3_ip_address: 10.250.253.1/24
lo0_ip_address: 10.255.0.103
site_traffic_rd: 10.255.0.103:1
site_traffic_neighbor_ip: 10.250.253.251
site_traffic_neighbor_asn: '65103'
bgp_password: $1c$G8BQN0ezkiJOX2cuAYpsEA==
