---

# WAN CV Pathfinder Settings

fabric_name: selab03
use_anta: true
deploy_to_cv_accept_preview: true
deploy_to_cv_inventory_host: cloudvision
bgp_update_wait_install: false

wan_mode: autovpn

bgp_as: 65014

cv_pathfinder_regions:
  - name: Global
    id: 1
    sites:
      - name: S-1A
        id: 100
      - name: S-2A
        id: 120
      - name: S-3A
        id: 130

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.10.0/31
      - 192.168.12.0/31
      - 192.168.13.0/31

wan_route_servers:
  - hostname: DC-RR1
    path_groups:
      - name: internet
        interfaces:
            - name: Ethernet1
              ip_address: 172.202.1.6

wan_ipsec_profiles:
  control_plane:
    shared_key: 0110100A480E0A0E231D1E
  data_plane:
    shared_key: 0110100A480E0A0E231D1E

wan_path_groups:
  - name: internet
    id: 101

wan_carriers:
  - name: internet
    path_group: internet
  - name: mpls
    path_group: mpls

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 101
    - name: prod
      policy: PROD-AVT-POLICY
      wan_vni: 102
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [internet]
            preference: preferred
    - name: PROD-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [internet]
            preference: preferred
