---
- name: Deploy Configurations to Devices Using CloudVision Portal
  hosts: CVAAS
  gather_facts: false
  connection: local

  tasks:

    - name: Deploying configurations to CVaaS
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        cv_collection: v3
        fabric_name: HARDWARE
        # container_root: 'DC1_FABRIC'
        configlets_prefix: 'CONFIGS'
        # state: present
        execute_tasks: true